# Generated by Django 2.1.7 on 2019-03-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20190329_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
