# Generated by Django 2.1.7 on 2019-03-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
