# Generated by Django 2.1.7 on 2019-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190329_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isemailverified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='isphoneverified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
